In [7]:
# Import
import numpy as np

In [8]:
# Broadcasting with Scalars

# Create array
arr = np.array([1, 2, 3, 4, 5])

# Scalar addition
result = arr + 10

print("Original:", arr)
print("After adding scalar:", result)

# A scalar is applied to every element of the array.

Original: [1 2 3 4 5]
After adding scalar: [11 12 13 14 15]


In [9]:
#Broadcasting Between 1D Arrays

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a:", a)
print("b:", b)

print("Addition:", a + b)

# Arrays must have same length or compatible shapes.

a: [1 2 3]
b: [10 20 30]
Addition: [11 22 33]


In [10]:
#Broadcasting (2D + 1D)

# 2D array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 1D array
row = np.array([10, 20, 30])

print("Matrix:\n", matrix)
print("Row:", row)

print("Result:\n", matrix + row)

Matrix:
 [[1 2 3]
 [4 5 6]]
Row: [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]]


In [11]:
# Shape understanding

print("Matrix shape:", matrix.shape)
print("Row shape:", row.shape)

# NumPy aligns shapes from right to left.

Matrix shape: (2, 3)
Row shape: (3,)


In [12]:
# Column Broadcasting 

col = np.array([[10], [20]])

print("Column:\n", col)
print("Result:\n", matrix + col)

Column:
 [[10]
 [20]]
Result:
 [[11 12 13]
 [24 25 26]]


Final Conclusion

Broadcasting allows NumPy to perform operations on arrays of different shapes.
It works by expanding smaller arrays without copying data.
Understanding shapes helps avoid errors and write efficient code.